---
  - name: Installing Unzip command
    yum: name=unzip state=latest

  - name: Install EPEL Yum Repository
    include: "{{plays_folder}}/install_rpm.yml"
    vars:
      rpm_app_name: "EPEL YUM Repository"
      rpm_filename : epel-release-7-5.noarch.rpm
