---
  - name: Creating the GOGS installation folder
    file:
      path=/usr/local/gogs
      state=directory
      owner=vagrant
      mode=0777

  - name: Copying GOGS to the host machine
    copy:
      src=../../../files/cache/{{gogs_zipfile}}
      dest=/tmp/{{gogs_zipfile}}

  - name: Unzipping the GOGS archive
    unarchive:
      src=/tmp/{{gogs_zipfile}}
      dest=/usr/local
      copy=no

  - name: Creating the GOGS custom configuration folder
    file:
      path=/usr/local/gogs/custom/conf
      state=directory
      owner=vagrant
      mode=0777

  - name: Copying GOGS custom configuration file
    template: src=app.ini.j2
              dest=/usr/local/gogs/custom/conf/app.ini
              mode=0755

  - name: Creating the GOGS "log" folder
    file:
      path=/usr/local/gogs/log
      state=directory
      owner=vagrant
      mode=0777

  - name: Removing the GOGS archive
    file:
      path=/tmp/{{gogs_zipfile}}
      state=absent

  - name: Creating the GOGS database
    mysql_db:
      state=import
      name=mysql
      target=/usr/local/gogs/scripts/mysql.sql

  - name: Installing GOGS service
    copy:
      src=gogs.service
      dest=/etc/systemd/system/gogs.service
      mode=0755

  - name: Starting the GOGS service
    service: 
      name=gogs
      state=started
      enabled=yes

  - name: Copying example repositories to the host
    copy: 
      src=gogs-repositories.zip 
      dest=/tmp

  - name: Unzipping GOGS repositories
    unarchive:
      src=/tmp/gogs-repositories.zip
      dest=/home/vagrant/
      copy=no
      owner=vagrant

  - name: Removing GOGS repositories from the host
    file: path=/tmp/gogs-repositories.zip state=absent

