---
- name: Create directory for Docker proxy settings
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Create Docker proxy settings file
  template:
    name: http-proxy.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
