---
  - name: Install glibc libraries
    yum:
      name=glibc.i686
      state=latest

  - name: Install pam libraries
    yum:
      name=pam.i686
      state=latest

  - name: Create group for GOGS user
    user:
      name="{{gogs_group}}"
      state=present

  - name: Create user for GOGS
    user:
      name="{{gogs_user}}"
      password="{{gogs_password}}"
      state=present

  - name: Creating the GOGS installation folder
    file:
      path="{{gogs_path}}"
      state=directory
      owner="{{gogs_user}}"
      group="{{gogs_group}}"
      mode=0755

  - name: Copying GOGS to the host machine
    copy:
      src=cache/{{gogs_zipfile}}
      dest=/tmp/{{gogs_zipfile}}

  - name: Unzipping the GOGS archive
    unarchive:
      src=/tmp/{{gogs_zipfile}}
      dest=/usr/local
      owner={{gogs_user}}
      group="{{gogs_group}}"
      copy=no

  - name: Creating the GOGS custom configuration folder
    file:
      path="{{gogs_path}}/custom/conf"
      state=directory
      owner="{{gogs_user}}"
      group="{{gogs_group}}"
      mode=0777

  - name: Copying GOGS custom configuration file
    template:
      src=app.ini.j2
      dest="{{gogs_path}}/custom/conf/app.ini"
      owner="{{gogs_user}}"
      group="{{gogs_group}}"
      mode=0755

  - name: Creating the GOGS "log" folder
    file:
      path="{{gogs_path}}/log"
      state=directory
      owner="{{gogs_user}}"
      group="{{gogs_group}}"
      mode=0777

  - name: Removing the GOGS archive
    file:
      path=/tmp/{{gogs_zipfile}}
      state=absent

  - name: Copying smoke test repository zip file to the host
    copy: 
      src=gogs-repositories.zip 
      dest=/tmp

  - name: Unzipping smoke repository
    unarchive:
      src=/tmp/gogs-repositories.zip
      dest=/home/{{gogs_user}}/
      owner="{{gogs_user}}"
      group="{{gogs_group}}"
      copy=no

  - name: Removing smoke test repository zip file from the host
    file:
      path=/tmp/gogs-repositories.zip
      state=absent

  - name: Clone PAMM seed repository
    include: install_pamm_seed.yml
    when: pamm == "yes"

  - name: Installing GOGS service
    copy:
      src=gogs.service
      dest=/etc/systemd/system/gogs.service
      mode=0755

  - name: Starting the GOGS service
    service:
      name=gogs
      state=started
      enabled=yes
    when: blueprint != "silicon"

  - name: Start GOGS
    shell: "su -c \"/usr/local/gogs/gogs web &\" - gogs"
    when: blueprint == "silicon"
