---
# This play installs GOGS - source code repository tool
#

### Install Git (GOGS)
  # Check if GIT has been installed
  - name: Check if Git installed
    stat: path=/bin/git
    register: git_exists

  - name: Install Git
    include: install_git.yml
    when: git_exists.stat.exists == false

### Install GOGS
  - name: Check GOGS installed
    stat: path=/usr/local/gogs
    register: gogs_exists
    changed_when: no

  - include: install_gogs.yml
    when: gogs_exists.stat.exists == false

