#
# Copyright (c) 2016 GATBLAU - www.gatblau.org
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Manages the execution of roles on a docker container.
# The only part of this playbook that needs changing is the list of roles as described below.
# The name of the playbook should be updated to reflect the host name - e.g. database.yml
#

#
# The playbook to deploy the Contnuous Integrations Tools Silver blueprint
#
---
- include: "plays/up_host.yml"
  vars:
    blueprint: silver

- name: Provisioning host ci-a
  hosts: ci-a
  connection: "{{connection}}"
  become: "{{become}}"
  roles:
    - nginx
    - jenkins_master
    - nexus

- name: Provisioning host ci-b
  hosts: ci-b
  connection: "{{connection}}"
  become: "{{become}}"
  roles:
    - nginx
    - jenkins_slave

- name: Provisioning host ci-c
  hosts: ci-c
  connection: "{{connection}}"
  become: "{{become}}"
  roles:
    - nginx
    - gogs
    - gerrit
    - sonar
    - mariadb