---
# This play contains variables for the ci_quality role

  sonar_user: sonar
  sonar_password: $6$rounds=656000$dCljFa3mpnaMQgzz$zHdLdm0wby6FMu4ISH0hFeoSecn/DH.E82yv8WLoGCb.8.Fw.pmiWVghMKliICh8PKCdYx1lCQvYyzb6I2VF10
  sonar_rpm: sonar-5.2-1.noarch.rpm

