---
# This play contains variables for the jenkins role

  # Jenkins RPM
  jenkins_rpm: jenkins-1.653-1.1.noarch.rpm

  # Jenkins folders
  jenkins_user_home: /home/jenkins
  jenkins_home: "{{jenkins_user_home}}/.jenkins"

  # Jenkins username and password
  jenkins_user: jenkins
  jenkins_password: $6$rounds=656000$vEwfQFfx8of8GbEK$.Ib42z9muqnJxiuQL/fw7JomQ5VXAPNBIWCQsQIm1nBIa/Jy17dXT3mxzwiI.BJ4mVdzJ2COlhlXmgn0EIaEz1
  jenkins_group: jenkins

  # Remote host settings for "publish over ssh" plugin
  remote_host_name: Development Integration Test
  remote_ip_address: "{{ lookup('file', 'cache/ci-dit-ip.txt') }}"

  # Jenkins Plugins
  jenkins_plugins:
    [
      'ansible.hpi',
      'artifactory.hpi',
      'config-file-provider.hpi',
      'credentials.hpi',
      'delivery-pipeline-plugin.hpi',
      'docker-build-step.hpi',
      'docker-commons.hpi',
      'email-ext.hpi',
      'envinject.hpi',
      'git.hpi',
      'git-client.hpi',
      'git-server.hpi',
      'gradle.hpi',
      'jquery.hpi',
      'parameterized-trigger.hpi',
      'publish-over-ssh.hpi',
      'sbt.hpi',
      'sonar.hpi',
      'ssh-credentials.hpi',
      'ssh-slaves.hpi',
      'teamconcert.hpi',
      'token-macro.hpi',
      'versionnumber.hpi',
      'ws-cleanup.hpi',
      'workflow-aggregator.hpi',
      'workflow-job.hpi',
      'workflow-step-api.hpi',
      'workflow-cps.hpi',
      'workflow-support.hpi',
      'workflow-durable-task-step.hpi',
      'workflow-basic-steps.hpi',
      'workflow-scm-step.hpi',
      'workflow-api.hpi',
      'workflow-cps-global-lib.hpi'
    ]

### Build tools variables
  git_perl_rpm: perl-Git-2.4.1-1.WANdisco.259.noarch.rpm
  git_scm_rpm: git-2.4.1-1.WANdisco.259.x86_64.rpm
  git_wandisco_rpm: wandisco-git-release-7-1.noarch.rpm

  gradle_folder: gradle-2.7
  gradle_zip: gradle-2.7-bin.zip

  groovy_folder: groovy-2.4.4
  groovy_zip: apache-groovy-binary-2.4.4.zip

  maven_folder: apache-maven-3.3.9
  maven_zip: apache-maven-3.3.9-bin.zip

  nodejs_rpm: nodejs-0.10.42-4.el7.x86_64.rpm
  npm_rpm: npm-1.3.6-5.el7.noarch.rpm

  perl_rpm: perl-5.16.3-286.el7.x86_64.rpm

  sbt_folder: sbt-0.13.11
  sbt_zip: sbt-0.13.11.zip

  sonar_runner_folder: sonar-runner-2.4
  sonar_runner_zipfile: sonar-runner-dist-2.4.zip

