---
  - include: "{{plays_folder}}/install_rpm.yml"
    vars:
      rpm_app_name: DOCKER
      rpm_filename: "{{ docker_rpm }}"

  - name: Starting the Docker daemon
    service:
      name=docker
      state=started
      enabled=yes
