---
  dependencies:
    - { role: baseline }
    - { role: jdk }
    - { role: jenkins_user }
    - { role: jenkins_install }
    - { role: jenkins_browsers,    when: "blueprint != 'silicon'" }
    - { role: jenkins_build_tools, when: "blueprint != 'silicon'" }
