---
# This play installs the Intellij Idea IDE
  - include: ../../../install_tool.yml
    vars:
      tool_name : IntelliJ
      folder_name : idea-IU-141.1532.4
      zip_filename: ideaIU-14.1.4.tar.gz
      add_version_to_folder : false
      zip_has_folder : true
      has_bin_folder : true

  - name: Creating Desktop Icon folder
    file:
      path=/usr/share/applications
      state=directory
      mode=0755

  - name: Copying IntelliJ Desktop Icon
    copy:
      src=intellij/intellij.desktop
      dest=dest=/usr/share/applications/intellij.desktop
    ignore_errors: yes
